/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventsRouteRouteImport } from './routes/events/route'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as ApiRevalidateRouteImport } from './routes/api/revalidate'
import { Route as CalendarIndexRouteImport } from './routes/calendar/index'
import { Route as DownloadIndexRouteImport } from './routes/download/index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as EventsEventIdRouteImport } from './routes/events/$eventId'
import { Route as MemberIndexRouteImport } from './routes/member/index'
import { Route as RegulationIndexRouteImport } from './routes/regulation/index'
import { Route as VideoIndexRouteImport } from './routes/video/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRouteRoute = EventsRouteRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRevalidateRoute = ApiRevalidateRouteImport.update({
  id: '/api/revalidate',
  path: '/api/revalidate',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarIndexRoute = CalendarIndexRouteImport.update({
  id: '/calendar/',
  path: '/calendar/',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadIndexRoute = DownloadIndexRouteImport.update({
  id: '/download/',
  path: '/download/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EventsRouteRoute,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/$eventId',
  path: '/$eventId',
  getParentRoute: () => EventsRouteRoute,
} as any)
const MemberIndexRoute = MemberIndexRouteImport.update({
  id: '/member/',
  path: '/member/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegulationIndexRoute = RegulationIndexRouteImport.update({
  id: '/regulation/',
  path: '/regulation/',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoIndexRoute = VideoIndexRouteImport.update({
  id: '/video/',
  path: '/video/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/events': typeof EventsRouteRouteWithChildren
  '/api/revalidate': typeof ApiRevalidateRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/about/': typeof AboutIndexRoute
  '/calendar/': typeof CalendarIndexRoute
  '/download/': typeof DownloadIndexRoute
  '/events/': typeof EventsIndexRoute
  '/member/': typeof MemberIndexRoute
  '/regulation/': typeof RegulationIndexRoute
  '/video/': typeof VideoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/revalidate': typeof ApiRevalidateRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/about': typeof AboutIndexRoute
  '/calendar': typeof CalendarIndexRoute
  '/download': typeof DownloadIndexRoute
  '/events': typeof EventsIndexRoute
  '/member': typeof MemberIndexRoute
  '/regulation': typeof RegulationIndexRoute
  '/video': typeof VideoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/events': typeof EventsRouteRouteWithChildren
  '/api/revalidate': typeof ApiRevalidateRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/about/': typeof AboutIndexRoute
  '/calendar/': typeof CalendarIndexRoute
  '/download/': typeof DownloadIndexRoute
  '/events/': typeof EventsIndexRoute
  '/member/': typeof MemberIndexRoute
  '/regulation/': typeof RegulationIndexRoute
  '/video/': typeof VideoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/events'
    | '/api/revalidate'
    | '/events/$eventId'
    | '/about/'
    | '/calendar/'
    | '/download/'
    | '/events/'
    | '/member/'
    | '/regulation/'
    | '/video/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/revalidate'
    | '/events/$eventId'
    | '/about'
    | '/calendar'
    | '/download'
    | '/events'
    | '/member'
    | '/regulation'
    | '/video'
  id:
    | '__root__'
    | '/'
    | '/events'
    | '/api/revalidate'
    | '/events/$eventId'
    | '/about/'
    | '/calendar/'
    | '/download/'
    | '/events/'
    | '/member/'
    | '/regulation/'
    | '/video/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EventsRouteRoute: typeof EventsRouteRouteWithChildren
  ApiRevalidateRoute: typeof ApiRevalidateRoute
  AboutIndexRoute: typeof AboutIndexRoute
  CalendarIndexRoute: typeof CalendarIndexRoute
  DownloadIndexRoute: typeof DownloadIndexRoute
  MemberIndexRoute: typeof MemberIndexRoute
  RegulationIndexRoute: typeof RegulationIndexRoute
  VideoIndexRoute: typeof VideoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/revalidate': {
      id: '/api/revalidate'
      path: '/api/revalidate'
      fullPath: '/api/revalidate'
      preLoaderRoute: typeof ApiRevalidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar/': {
      id: '/calendar/'
      path: '/calendar'
      fullPath: '/calendar/'
      preLoaderRoute: typeof CalendarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download/': {
      id: '/download/'
      path: '/download'
      fullPath: '/download/'
      preLoaderRoute: typeof DownloadIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof EventsRouteRoute
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof EventsRouteRoute
    }
    '/member/': {
      id: '/member/'
      path: '/member'
      fullPath: '/member/'
      preLoaderRoute: typeof MemberIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regulation/': {
      id: '/regulation/'
      path: '/regulation'
      fullPath: '/regulation/'
      preLoaderRoute: typeof RegulationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video/': {
      id: '/video/'
      path: '/video'
      fullPath: '/video/'
      preLoaderRoute: typeof VideoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface EventsRouteRouteChildren {
  EventsEventIdRoute: typeof EventsEventIdRoute
  EventsIndexRoute: typeof EventsIndexRoute
}

const EventsRouteRouteChildren: EventsRouteRouteChildren = {
  EventsEventIdRoute: EventsEventIdRoute,
  EventsIndexRoute: EventsIndexRoute,
}

const EventsRouteRouteWithChildren = EventsRouteRoute._addFileChildren(
  EventsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EventsRouteRoute: EventsRouteRouteWithChildren,
  ApiRevalidateRoute: ApiRevalidateRoute,
  AboutIndexRoute: AboutIndexRoute,
  CalendarIndexRoute: CalendarIndexRoute,
  DownloadIndexRoute: DownloadIndexRoute,
  MemberIndexRoute: MemberIndexRoute,
  RegulationIndexRoute: RegulationIndexRoute,
  VideoIndexRoute: VideoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
