/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as EquestrianRouteImport } from './routes/equestrian'
import { Route as EventsRouteImport } from './routes/events'
import { Route as MemberRouteImport } from './routes/member'
import { Route as RegulationRouteImport } from './routes/regulation'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as AboutConstitutionRouteImport } from './routes/about/constitution'
import { Route as AboutHistoryRouteImport } from './routes/about/history'
import { Route as AboutMissionRouteImport } from './routes/about/mission'
import { Route as AboutVisionRouteImport } from './routes/about/vision'
import { Route as ApiRevalidateRouteImport } from './routes/api/revalidate'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as EventsEventIdRouteImport } from './routes/events.$eventId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const EquestrianRoute = EquestrianRouteImport.update({
  id: '/equestrian',
  path: '/equestrian',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberRoute = MemberRouteImport.update({
  id: '/member',
  path: '/member',
  getParentRoute: () => rootRouteImport,
} as any)
const RegulationRoute = RegulationRouteImport.update({
  id: '/regulation',
  path: '/regulation',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AboutRoute,
} as any)
const AboutConstitutionRoute = AboutConstitutionRouteImport.update({
  id: '/constitution',
  path: '/constitution',
  getParentRoute: () => AboutRoute,
} as any)
const AboutHistoryRoute = AboutHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AboutRoute,
} as any)
const AboutMissionRoute = AboutMissionRouteImport.update({
  id: '/mission',
  path: '/mission',
  getParentRoute: () => AboutRoute,
} as any)
const AboutVisionRoute = AboutVisionRouteImport.update({
  id: '/vision',
  path: '/vision',
  getParentRoute: () => AboutRoute,
} as any)
const ApiRevalidateRoute = ApiRevalidateRouteImport.update({
  id: '/api/revalidate',
  path: '/api/revalidate',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EventsRoute,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/$eventId',
  path: '/$eventId',
  getParentRoute: () => EventsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/calendar': typeof CalendarRoute
  '/download': typeof DownloadRoute
  '/equestrian': typeof EquestrianRoute
  '/events': typeof EventsRouteWithChildren
  '/member': typeof MemberRoute
  '/regulation': typeof RegulationRoute
  '/about/constitution': typeof AboutConstitutionRoute
  '/about/history': typeof AboutHistoryRoute
  '/about/mission': typeof AboutMissionRoute
  '/about/vision': typeof AboutVisionRoute
  '/api/revalidate': typeof ApiRevalidateRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/about/': typeof AboutIndexRoute
  '/events/': typeof EventsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/download': typeof DownloadRoute
  '/equestrian': typeof EquestrianRoute
  '/member': typeof MemberRoute
  '/regulation': typeof RegulationRoute
  '/about/constitution': typeof AboutConstitutionRoute
  '/about/history': typeof AboutHistoryRoute
  '/about/mission': typeof AboutMissionRoute
  '/about/vision': typeof AboutVisionRoute
  '/api/revalidate': typeof ApiRevalidateRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/about': typeof AboutIndexRoute
  '/events': typeof EventsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/calendar': typeof CalendarRoute
  '/download': typeof DownloadRoute
  '/equestrian': typeof EquestrianRoute
  '/events': typeof EventsRouteWithChildren
  '/member': typeof MemberRoute
  '/regulation': typeof RegulationRoute
  '/about/constitution': typeof AboutConstitutionRoute
  '/about/history': typeof AboutHistoryRoute
  '/about/mission': typeof AboutMissionRoute
  '/about/vision': typeof AboutVisionRoute
  '/api/revalidate': typeof ApiRevalidateRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/about/': typeof AboutIndexRoute
  '/events/': typeof EventsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/calendar'
    | '/download'
    | '/equestrian'
    | '/events'
    | '/member'
    | '/regulation'
    | '/about/constitution'
    | '/about/history'
    | '/about/mission'
    | '/about/vision'
    | '/api/revalidate'
    | '/events/$eventId'
    | '/about/'
    | '/events/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/download'
    | '/equestrian'
    | '/member'
    | '/regulation'
    | '/about/constitution'
    | '/about/history'
    | '/about/mission'
    | '/about/vision'
    | '/api/revalidate'
    | '/events/$eventId'
    | '/about'
    | '/events'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/calendar'
    | '/download'
    | '/equestrian'
    | '/events'
    | '/member'
    | '/regulation'
    | '/about/constitution'
    | '/about/history'
    | '/about/mission'
    | '/about/vision'
    | '/api/revalidate'
    | '/events/$eventId'
    | '/about/'
    | '/events/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRouteWithChildren
  CalendarRoute: typeof CalendarRoute
  DownloadRoute: typeof DownloadRoute
  EquestrianRoute: typeof EquestrianRoute
  EventsRoute: typeof EventsRouteWithChildren
  MemberRoute: typeof MemberRoute
  RegulationRoute: typeof RegulationRoute
  ApiRevalidateRoute: typeof ApiRevalidateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equestrian': {
      id: '/equestrian'
      path: '/equestrian'
      fullPath: '/equestrian'
      preLoaderRoute: typeof EquestrianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member': {
      id: '/member'
      path: '/member'
      fullPath: '/member'
      preLoaderRoute: typeof MemberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regulation': {
      id: '/regulation'
      path: '/regulation'
      fullPath: '/regulation'
      preLoaderRoute: typeof RegulationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/constitution': {
      id: '/about/constitution'
      path: '/constitution'
      fullPath: '/about/constitution'
      preLoaderRoute: typeof AboutConstitutionRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/history': {
      id: '/about/history'
      path: '/history'
      fullPath: '/about/history'
      preLoaderRoute: typeof AboutHistoryRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/mission': {
      id: '/about/mission'
      path: '/mission'
      fullPath: '/about/mission'
      preLoaderRoute: typeof AboutMissionRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/vision': {
      id: '/about/vision'
      path: '/vision'
      fullPath: '/about/vision'
      preLoaderRoute: typeof AboutVisionRouteImport
      parentRoute: typeof AboutRoute
    }
    '/api/revalidate': {
      id: '/api/revalidate'
      path: '/api/revalidate'
      fullPath: '/api/revalidate'
      preLoaderRoute: typeof ApiRevalidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof EventsRoute
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof EventsRoute
    }
  }
}

interface AboutRouteChildren {
  AboutConstitutionRoute: typeof AboutConstitutionRoute
  AboutHistoryRoute: typeof AboutHistoryRoute
  AboutMissionRoute: typeof AboutMissionRoute
  AboutVisionRoute: typeof AboutVisionRoute
  AboutIndexRoute: typeof AboutIndexRoute
}

const AboutRouteChildren: AboutRouteChildren = {
  AboutConstitutionRoute: AboutConstitutionRoute,
  AboutHistoryRoute: AboutHistoryRoute,
  AboutMissionRoute: AboutMissionRoute,
  AboutVisionRoute: AboutVisionRoute,
  AboutIndexRoute: AboutIndexRoute,
}

const AboutRouteWithChildren = AboutRoute._addFileChildren(AboutRouteChildren)

interface EventsRouteChildren {
  EventsEventIdRoute: typeof EventsEventIdRoute
  EventsIndexRoute: typeof EventsIndexRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsEventIdRoute: EventsEventIdRoute,
  EventsIndexRoute: EventsIndexRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRouteWithChildren,
  CalendarRoute: CalendarRoute,
  DownloadRoute: DownloadRoute,
  EquestrianRoute: EquestrianRoute,
  EventsRoute: EventsRouteWithChildren,
  MemberRoute: MemberRoute,
  RegulationRoute: RegulationRoute,
  ApiRevalidateRoute: ApiRevalidateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
